#!/bin/bash

if [ -z "$DRICH_DEV" ]; then echo "ERROR: source environ.sh first"; exit 1; fi

export DETECTOR=athena
export DETECTOR_PATH=$EIC_SHELL_PREFIX/share/$DETECTOR
export DETECTOR_CONFIG=$DETECTOR

export JUGGLER_DETECTOR=$DETECTOR
export JUGGLER_DETECTOR_CONFIG=$DETECTOR_CONFIG
export JUGGLER_DETECTOR_PATH=$DETECTOR_PATH
export JUGGLER_INSTALL_PREFIX=$EIC_SHELL_PREFIX
export JUGGLER_N_THREADS=$BUILD_NPROC

export PS1="${PS1:-}"
export PS1="ATHENA dRICH${PS1_SIGIL}>${PS1#*>}"
unset branch

echo """


     ###########################################
     ###    dRICH Development Environment    ###
     ###########################################

Beam:
  BEAMLINE_PATH           = $BEAMLINE_PATH
  BEAMLINE_CONFIG         = $BEAMLINE_CONFIG
  BEAMLINE_CONFIG_VERSION = $BEAMLINE_CONFIG_VERSION

Detector:
  DETECTOR         = $DETECTOR
  DETECTOR_PATH    = $DETECTOR_PATH
  DETECTOR_CONFIG  = $DETECTOR_CONFIG
  DETECTOR_VERSION = $DETECTOR_VERSION

Packages:
  IRT_ROOT  = $IRT_ROOT
  EICD_ROOT = $EICD_ROOT

Juggler (to be deprecated):
  JUGGLER_INSTALL_PREFIX   = $JUGGLER_INSTALL_PREFIX
  JUGGLER_DETECTOR         = $JUGGLER_DETECTOR
  JUGGLER_DETECTOR_PATH    = $JUGGLER_DETECTOR_PATH
  JUGGLER_DETECTOR_CONFIG  = $JUGGLER_DETECTOR_CONFIG
  JUGGLER_DETECTOR_VERSION = $JUGGLER_DETECTOR_VERSION
  JUGGLER_DETECTOR_PATH    = $JUGGLER_DETECTOR_PATH
  JUGGLER_BEAMLINE_CONFIG  = $JUGGLER_BEAMLINE_CONFIG
  JUGGLER_BEAMLINE_CONFIG_VERSION = $JUGGLER_BEAMLINE_CONFIG_VERSION

LD_LIBRARY_PATH:
  $(echo $LD_LIBRARY_PATH | sed 's/:/\n  /g')

Common:
  DRICH_DEV        = $DRICH_DEV
  BUILD_NPROC      = $BUILD_NPROC
  EIC_SHELL_PREFIX = $EIC_SHELL_PREFIX
  DETECTOR_PATH    = $DETECTOR_PATH

"""
